package org.ace.insurance.web.common.myanmarLanguae;

public class MyanamarConstant {
	public static final String LIFEENDORSEMENT_ISSUE_LABEL_02 = "LIFEENDORSEMENT_ISSUE_LABEL_02";
	public static final String LIFEENDORSEMENT_ISSUE_LABEL_03 = "LIFEENDORSEMENT_ISSUE_LABEL_03";
	public static final String LIFEENDORSEMENT_ISSUE_LABEL_04 = "LIFEENDORSEMENT_ISSUE_LABEL_04";
	public static final String LIFEENDORSEMENT_ISSUE_LABEL_05 = "LIFEENDORSEMENT_ISSUE_LABEL_05";
	public static final String LIFEENDORSEMENT_ISSUE_LABEL_06 = "LIFEENDORSEMENT_ISSUE_LABEL_06";
	public static final String LIFEENDORSEMENT_ISSUE_LABEL_07 = "LIFEENDORSEMENT_ISSUE_LABEL_07";
	public static final String LIFEENDORSEMENT_ISSUE_LABEL_08 = "LIFEENDORSEMENT_ISSUE_LABEL_08";
	public static final String LIFEENDORSEMENT_ISSUE_LABEL_09 = "LIFEENDORSEMENT_ISSUE_LABEL_09";
}
