package org.ace.insurance.system.common.agent;

public class COACode {
	public static final String CASH = "CASH";

	/* For TLF Import */
	public static final String PAYMENT_VARIABLE_ACNAME = "PAYMENT_VARIABLE_ACNAME";
	public static final String INTER_BRANCH_CSC = "INTER_BRANCH_CSC";
	public static final String INTERBRANCH_SUNDRY = "INTERBRANCH_SUNDRY";

	public static final String AGENT_WITHHOLDING_TAX = "AGENT_WITHHOLDING_TAX";

	/* Motor */
	public static final String MOTOR_RECEIVABLE = "MOTOR_RECEIVABLE";
	public static final String MOTOR_SERVICE_CHARGES = "MOTOR_SERVICE_CHARGES";
	public static final String MOTOR_STAMP_FEE = "MOTOR_STAMP_FEE";
	public static final String MOTOR_SUNDRY = "MOTOR_SUNDRY";
	public static final String MOTOR_PREMIUM = "MOTOR_PREMIUM";
	public static final String MOTOR_AGENT_COMMISSION = "MOTOR_AGENT_COMMISSION";
	public static final String MOTOR_AGENT_PAYABLE = "MOTOR_AGENT_PAYABLE";
	public static final String MOTOR_COINWARD_RECEIVABLE = "MOTOR_COINWARD_RECEIVABLE";
	public static final String MOTOR_COINWARD_COMMISSION = "MOTOR_COINWARD_COMMISSION";
	public static final String MOTOR_COOUTWARD_COMMISSION = "MOTOR_COOUTWARD_COMMISSION";
	public static final String MOTOR_COINWARD_PAYABLE = "MOTOR_COINWARD_PAYABLE";
	public static final String MOTOR_CLAIM = "MOTOR_CLAIM";
	public static final String MOTOR_CLAIM_DEATH = "MOTOR_CLAIM_DEATH";
	public static final String MOTOR_CO_AGENT_PAYABLE = "MOTOR_CO_AGENT_PAYABLE";
	public static final String MOTOR_COINSURANCE_COMMISSION = "MOTOR_COINSURANCE_COMMISSION";
	public static final String MOTOR_COINSURANCE_PREMIUM = "MOTOR_COINSURANCE_PREMIUM";
	public static final String MOTOR_CLAIM_OUTSTANDING = "MOTOR_CLAIM_OUTSTANDING";
	public static final String MOTOR_REINSTATE_PREMIUM = "MOTOR_REINSTATE_PREMIUM";

	/* Fire */
	public static final String FIRE_DECLARATION_PREMIUM = "FIRE_DECLARATION_PREMIUM";
	public static final String FIRE_PREMIUM = "FIRE_PREMIUM";
	public static final String FIRE_SUNDRY = "FIRE_SUNDRY";
	public static final String FIRE_RECEIVABLE = "FIRE_RECEIVABLE";
	public static final String FIRE_AGENT_COMMISSION = "FIRE_AGENT_COMMISSION";
	public static final String FIRE_AGENT_PAYABLE = "FIRE_AGENT_PAYABLE";
	public static final String FIRE_COINSURANCE_COMMISSION = "FIRE_COINSURANCE_COMMISSION";
	public static final String FIRE_COINSURANCE_PREMIUM = "FIRE_COINSURANCE_PREMIUM";
	public static final String FIRE_CO_AGENT_PAYABLE = "FIRE_CO_AGENT_PAYABLE";
	public static final String FIRE_SERVICE_CHARGES = "FIRE_SERVICE_CHARGES";
	public static final String FIRE_STAMP_FEES = "FIRE_STAMP_FEES";
	public static final String FIRE_CLAIM = "FIRE_CLAIM";
	public static final String FIRE_COINWARD_RECEIVABLE = "FIRE_COINWARD_RECEIVABLE";
	public static final String FIRE_COINWARD_COMMISSION = "FIRE_COINWARD_COMMISSION";
	public static final String FIRE_COOUTWARD_COMMISSION = "FIRE_COOUTWARD_COMMISSION";
	public static final String FIRE_COINWARD_PAYABLE = "FIRE_COINWARD_PAYABLE";

	/* Fidelity */
	public static final String FIDELITY_SERVICE_CHARGES = "FIDELITY_SERVICE_CHARGES";
	public static final String FIDELITY_COINWARD_RECEIVABLE = "FIDELITY_COINWARD_RECEIVABLE";
	public static final String FIDELITY_SUNDRY = "FIDELITY_SUNDRY";
	public static final String FIDELITY_STAMP_FEES = "FIDELITY_STAMP_FEES";
	public static final String FIDELITY_COINWARD_COMMISSION = "FIDELITY_COINWARD_COMMISSION";
	public static final String FIDELITY_COINWARD_PAYABLE = "FIDELITY_COINWARD_PAYABLE";
	public static final String FIDELITY_RECEIVABLE = "FIDELITY_RECEIVABLE";
	public static final String FIDELITY_AGENT_COMMISSION = "FIDELITY_AGENT_COMMISSION";
	public static final String FIDELITY_AGENT_PAYABLE = "FIDELITY_AGENT_PAYABLE";
	public static final String FIDELITY_PREMIUM = "FIDELITY_PREMIUM";

	/* Cash In Safe */
	public static final String CASH_IN_SAFE_SERVICE_CHARGES = "CASH_IN_SAFE_SERVICE_CHARGES";
	public static final String CASH_IN_SAFE_COINWARD_RECEIVABLE = "CASH_IN_SAFE_COINWARD_RECEIVABLE";
	public static final String CASH_IN_SAFE_SUNDRY = "CASH_IN_SAFE_SUNDRY";
	public static final String CASH_IN_SAFE_STAMP_FEES = "CASH_IN_SAFE_STAMP_FEES";
	public static final String CASH_IN_SAFE_COINWARD_COMMISSION = "CASH_IN_SAFE_COINWARD_COMMISSION";
	public static final String CASH_IN_SAFE_COINWARD_PAYABLE = "CASH_IN_SAFE_COINWARD_PAYABLE";
	public static final String CASH_IN_SAFE_RECEIVABLE = "CASH_IN_SAFE_RECEIVABLE";
	public static final String CASH_IN_SAFE_AGENT_COMMISSION = "CASH_IN_SAFE_AGENT_COMMISSION";
	public static final String CASH_IN_SAFE_AGENT_PAYABLE = "CASH_IN_SAFE_AGENT_PAYABLE";
	public static final String CASH_IN_SAFE_PREMIUM = "CASH_IN_SAFE_PREMIUM";
	public static final String CASH_IN_SAFE_CLAIM = "CASH_IN_SAFE_CLAIM";

	/* Cash In Transit */
	public static final String CASH_IN_TRANSIT_SERVICE_CHARGES = "CASH_IN_TRANSIT_SERVICE_CHARGES";
	public static final String CASH_IN_TRANSIT_PREMIUM = "CASH_IN_TRANSIT_PREMIUM";
	public static final String CASH_IN_TRANSIT_COINWARD_RECEIVABLE = "CASH_IN_TRANSIT_COINWARD_RECEIVABLE";
	public static final String CASH_IN_TRANSIT_CLAIM = "CASH_IN_TRANSIT_CLAIM";
	public static final String CASH_IN_TRANSIT_RECEIVABLE = "CASH_IN_TRANSIT_RECEIVABLE";
	public static final String CASH_IN_TRANSIT_AGENT_PAYABLE = "CASH_IN_TRANSIT_AGENT_PAYABLE";
	public static final String CASH_IN_TRANSIT_AGENT_COMMISSION = "CASH_IN_TRANSIT_AGENT_COMMISSION";
	public static final String CASH_IN_TRANSIT_SUNDRY = "CASH_IN_TRANSIT_SUNDRY";
	public static final String CASH_IN_TRANSIT_STAMP_FEES = "CASH_IN_TRANSIT_STAMP_FEES";
	public static final String CASH_IN_TRANSIT_COINWARD_PAYABLE = "CASH_IN_TRANSIT_COINWARD_PAYABLE";
	public static final String CASH_IN_TRANSIT_COINWARD_COMMISSION = "CASH_IN_TRANSIT_COINWARD_COMMISSION";

	/* Cargo */
	public static final String CARGO_RECEIVABLE = "CARGO_RECEIVABLE";
	public static final String CARGO_SERVICE_CHARGES = "CARGO_SERVICE_CHARGES";
	public static final String CARGO_STAMP_FEE = "CARGO_STAMP_FEE";
	public static final String CARGO_SUNDRY = "CARGO_SUNDRY";
	public static final String CARGO_PREMIUM = "CARGO_PREMIUM";
	public static final String CARGO_AGENT_COMMISSION = "CARGO_AGENT_COMMISSION";
	public static final String CARGO_AGENT_PAYABLE = "CARGO_AGENT_PAYABLE";
	public static final String CARGO_REINWARD_RECEIVABLE = "CARGO_REINWARD_RECEIVABLE";
	public static final String CARGO_REINWARD_COMMISSION = "CARGO_REINWARD_COMMISSION";
	public static final String CARGO_REINSURANCE_PREMIUM = "CARGO_REINSURANCE_PREMIUM";
	public static final String CARGO_STAMP_FEES = "CARGO_STAMP_FEES";
	public static final String CARGO_CLAIM = "CARGO_CLAIM";
	public static final String CARGO_AGENT_MISCELLANEOUS = "CARGO_AGENT_MISCELLANEOUS";

	public static final String CHEQUE = "CHEQUE";
	public static final String YANGON_INTERBRANCH = "YANGON_INTERBRANCH";
	public static final String STAMP_FEES = "STAMP_FEES";
	public static final String MEDICAL_FEES = "MEDICAL_FEES";

	/* Marine */
	public static final String MARINE_PREMIUM = "MARINE_PREMIUM";
	public static final String MARINE_COPREMIUM = "MARINE_COPREMIUM";
	public static final String MARINE_AGENT_COMMISSION = "MARINE_AGENT_COMMISSION";
	public static final String MARINE_AGENT_PAYABLE = "MARINE_AGENT_PAYABLE";
	public static final String MARINE_SERVICE_CHARGES = "MARINE_SERVICE_CHARGES";
	public static final String MARINE_RECEIVABLE = "MARINE_RECEIVABLE";
	public static final String MARINE_SUNDRY = "MARINE_SUNDRY";
	public static final String MARINE_COINSURANCE_COMMISSION = "MARINE_COINSURANCE_COMMISSION";
	public static final String MARINE_CO_PREMIUM = "MARINE_CO_PREMIUM";

	/* InLand */
	public static final String INLAND_PREMIUM = "INLAND_PREMIUM";
	public static final String INLAND_COPREMIUM = "INLAND_COPREMIUM";
	public static final String INLAND_AGENT_PAYABLE = "INLAND_AGENT_PAYABLE";
	public static final String INLAND_SERVICE_CHARGES = "INLAND_SERVICE_CHARGES";
	public static final String INLAND_RECEIVABLE = "INLAND_RECEIVABLE";
	public static final String INLAND_AGENT_COMMISSION = "INLAND_AGENT_COMMISSION";
	public static final String INLAND_SUNDRY = "INLAND_SUNDRY";
	public static final String INLAND_COINSURANCE_COMMISSION = "INLAND_COINSURANCE_COMMISSION";
	public static final String INLAND_CO_PREMIUM = "INLAND_CO_PREMIUM";

	/* Overseas Cargo */
	public static final String OVERSEAS_CARGO_PREMIUM = "OVERSEAS_CARGO_PREMIUM";
	public static final String OVERSEAS_CARGO_AGENT_PAYABLE = "OVERSEAS_CARGO_AGENT_PAYABLE";
	public static final String OVERSEAS_CARGO_AGENT_COMMISSION = "OVERSEAS_CARGO_AGENT_COMMISSION";
	public static final String OVERSEAS_CARGO_RECEIVABLE = "OVERSEAS_CARGO_RECEIVABLE";
	public static final String OVERSEAS_CARGO_SERVICE_CHARGES = "OVERSEAS_CARGO_SERVICE_CHARGES";
	public static final String OVERSEAS_CARGO_REINWARD_RECEIVABLE = "OVERSEAS_CARGO_REINWARD_RECEIVABLE";
	public static final String OVERSEAS_CARGO_REINWARD_COMMISSION = "OVERSEAS_CARGO_REINWARD_COMMISSION";
	public static final String OVERSEAS_CARGO_REINSURANCE_PREMIUM = "OVERSEAS_CARGO_REINSURANCE_PREMIUM";

	/* Marine Hull */
	public static final String HULLOVERSEAVOYAGE_AGENT_COMMISSION = "HULLOVERSEAVOYAGE_AGENT_COMMISSION";
	public static final String HULLOVERSEAVOYAGE_AGENT_PAYABLE = "HULLOVERSEAVOYAGE_AGENT_PAYABLE";
	public static final String HULLOVERSEAVOYAGE_PREMIUM = "HULLOVERSEAVOYAGE_PREMIUM";
	public static final String HULLOVERSEAVOYAGE_RECEIVABLE = "HULLOVERSEAVOYAGE_RECEIVABLE";
	public static final String HULLOVERSEAVOYAGE_SERVICE_CHARGES = "HULLOVERSEAVOYAGE_SERVICE_CHARGES";
	public static final String MARINEHULL_REINWARD_RECEIVE = "MARINEHULL_REINWARD_RECEIVE";
	public static final String MARINEHULL_REINWARD_COMMISSION = "MARINEHULL_REINWARD_COMMISSION";
	public static final String MARINEHULL_REINSURANCE_PREMIUM = "MARINEHULL_REINSURANCE_PREMIUM";

	public static final String HULLOVERSEATIME_AGENT_COMMISSION = "HULLOVERSEATIME_AGENT_COMMISSION";
	public static final String HULLOVERSEATIME_AGENT_PAYABLE = "HULLOVERSEATIME_AGENT_PAYABLE";
	public static final String HULLOVERSEATIME_PREMIUM = "HULLOVERSEATIME_PREMIUM";
	public static final String HULLOVERSEATIME_RECEIVABLE = "HULLOVERSEATIME_RECEIVABLE";
	public static final String HULLOVERSEATIME_SERVICE_CHARGES = "HULLOVERSEATIME_SERVICE_CHARGES";

	public static final String HULLINLANDTIME_AGENT_COMMISSION = "HULLINLANDTIME_AGENT_COMMISSION";
	public static final String HULLINLANDTIME_AGENT_PAYABLE = "HULLINLANDTIME_AGENT_PAYABLE";
	public static final String HULLINLANDTIME_PREMIUM = "HULLINLANDTIME_PREMIUM";
	public static final String HULLINLANDTIME_RECEIVABLE = "HULLINLANDTIME_RECEIVABLE";
	public static final String HULLINLANDTIME_SERVICE_CHARGES = "HULLINLANDTIME_SERVICE_CHARGES";

	public static final String HULLINLANDVOYAGE_AGENT_COMMISSION = "HULLINLANDVOYAGE_AGENT_COMMISSION";
	public static final String HULLINLANDVOYAGE_AGENT_PAYABLE = "HULLINLANDVOYAGE_AGENT_PAYABLE";
	public static final String HULLINLANDVOYAGE_PREMIUM = "HULLINLANDVOYAGE_PREMIUM";
	public static final String HULLINLANDVOYAGE_RECEIVABLE = "HULLINLANDVOYAGE_RECEIVABLE";
	public static final String HULLINLANDVOYAGE_SERVICE_CHARGES = "HULLINLANDVOYAGE_SERVICE_CHARGES";

	public static final String HULLINLANDWOODVOYAGE_AGENT_COMMISSION = "HULLINLANDWOODVOYAGE_AGENT_COMMISSION";
	public static final String HULLINLANDWOODVOYAGE_AGENT_PAYABLE = "HULLINLANDWOODVOYAGE_AGENT_PAYABLE";
	public static final String HULLINLANDWOODVOYAGE_PREMIUM = "HULLINLANDWOODVOYAGE_PREMIUM";
	public static final String HULLINLANDWOODVOYAGE_RECEIVABLE = "HULLINLANDWOODVOYAGE_RECEIVABLE";
	public static final String HULLINLANDWOODVOYAGE_SERVICE_CHARGES = "HULLINLANDWOODVOYAGE_SERVICE_CHARGES";

	public static final String MARINEHULL_STAMP_FEES = "MARINEHULL_STAMP_FEES";

	/* Travel */
	public static final String UNDER100_TRAVEL_PREMIUM = "UNDER100_TRAVEL_PREMIUM";
	public static final String PERSON_TRAVEL_PREMIUM = "PERSON_TRAVEL_PREMIUM";
	public static final String PERSON_TRAVEL_STAMP_FEE = "PERSON_TRAVEL_STAMP_FEE";
	public static final String PERSON_TRAVEL_SERVICE_CHARGES = "PERSON_TRAVEL_SERVICE_CHARGES";
	public static final String PERSON_TRAVEL_RECEIVABLE = "PERSON_TRAVEL_RECEIVABLE";
	public static final String UNDER100_TRAVEL_AGENT_COMMISSION = "UNDER100_TRAVEL_AGENT_COMMISSION";
	public static final String PERSON_TRAVEL_AGENT_COMMISSION = "PERSON_TRAVEL_AGENT_COMMISSION";
	public static final String PERSON_TRAVEL_AGENT_PAYABLE = "PERSON_TRAVEL_AGENT_PAYABLE";

	public static final String SPECIAL_TRAVEL_RECEIVABLE = "SPECIAL_TRAVEL_RECEIVABLE";
	public static final String SPECIAL_TRAVEL_PREMIUM = "SPECIAL_TRAVEL_PREMIUM";
	public static final String SPECIAL_TRAVEL_SERVICE_CHARGES = "SPECIAL_TRAVEL_SERVICE_CHARGES";
	public static final String SPECIAL_TRAVEL_AGENT_COMMISSION = "SPECIAL_TRAVEL_AGENT_COMMISSION";
	public static final String SPECIAL_TRAVEL_AGENT_PAYABLE = "SPECIAL_TRAVEL_AGENT_PAYABLE";

	/**/
	public static final String INTER_BRANCH_HO = "INTER_BRANCH_HO";
	public static final String MANDALAY_INTERBRANCH = "MANDALAY_INTERBRANCH";
	public static final String GOVERNMENT_STAMP_MARINE = "GOVERNMENT_STAMP_MARINE";

	/* Public Life */
	public static final String PUBLIC_LIFE_PREMIUM = "PUBLIC_LIFE_PREMIUM";
	public static final String PUBLIC_LIFE_RECEIVABLE = "PUBLIC_LIFE_RECEIVABLE";
	public static final String PUBLIC_LIFE_AGENT_COMMISSION = "PUBLIC_LIFE_AGENT_COMMISSION";
	public static final String PUBLIC_LIFE_AGENT_PAYABLE = "PUBLIC_LIFE_AGENT_PAYABLE";
	public static final String PUBLIC_LIFE_SERVICE_CHARGES = "PUBLIC_LIFE_SERVICE_CHARGES";
	public static final String PUBLIC_LIFE_STAMP_FEES = "PUBLIC_LIFE_STAMP_FEES";
	public static final String PUBLIC_LIFE_CLAIM = "PUBLIC_LIFE_CLAIM";
	public static final String PUBLIC_LIFE_CLAIM_PAYABLE = "PUBLIC_LIFE_CLAIM_PAYABLE";
	public static final String PUBLIC_LIFE_MEDICAL_FEES = "PUBLIC_LIFE_MEDICAL_FEES";
	public static final String PUBLIC_LIFE_MEDICAL_FEES_PAYABLE = "PUBLIC_LIFE_MEDICAL_FEES_PAYABLE";

	public static final String LIFE_SUNDRY = "LIFE_SUNDRY";
	public static final String LIFE_CO_AGENT_PAYABLE = "LIFE_CO_AGENT_PAYABLE";
	public static final String LIFE_COINSURANCE_COMMISSION = "LIFE_COINSURANCE_COMMISSION";
	public static final String LIFE_COINSURANCE_PREMIUM = "LIFE_COINSURANCE_PREMIUM";
	public static final String LIFE_CLAIM = "LIFE_CLAIM";
	public static final String LIFE_DISABILITY_CLAIM = "LIFE_DISABILITY_CLAIM";
	public static final String LIFE_SURRENDER_CLAIM = "LIFE_SURRENDER_CLAIM";
	public static final String LIFE_PAIDUP_CLAIM = "LIFE_PAIDUP_CLAIM";
	public static final String LIFE_INWARD_RECEIVE = "LIFE_INWARD_RECEIVE";
	public static final String LIFE_COINWARD_COMMISSION = "LIFE_COINWARD_COMMISSION";
	public static final String LIFE_COOUTWARD_COMMISSION = "LIFE_COOUTWARD_COMMISSION";

	/* Short Term Endownment */
	public static final String SHORT_ENDOWMENT_LIFE_PREMIUM = "SHORT_ENDOWMENT_LIFE_PREMIUM";
	public static final String SHORT_ENDOWMENT_RECEIVABLE = "SHORT_ENDOWMENT_RECEIVABLE";
	public static final String SHORT_ENDOWMENT_AGENT_COMMISSION = "SHORT_ENDOWMENT_AGENT_COMMISSION";
	public static final String SHORT_ENDOWMENT_AGENT_PAYABLE = "SHORT_ENDOWMENT_AGENT_PAYABLE";
	public static final String SHORT_ENDOWMENT_SERVICE_CHARGES = "SHORT_ENDOWMENT_SERVICE_CHARGES";
	public static final String SHORT_ENDOWMENT_STAMP_FEE = "SHORT_ENDOWMENT_STAMP_FEE";
	public static final String SHORT_ENDOWMENT_LIFE_CLAIM = "SHORT_ENDOWMENT_LIFE_CLAIM";
	public static final String SHORT_ENDOWMENT_LIFE_PAYABLE = "SHORT_ENDOWMENT_LIFE_PAYABLE";
	public static final String SHORT_ENDOWMENT_MEDICAL_FEES = "SHORT_ENDOWMENT_MEDICAL_FEES";
	public static final String SHORT_ENDOWMENT_MEDICAL_FEES_PAYABLE = "SHORT_ENDOWMENT_MEDICAL_FEES_PAYABLE";

	/* Student Life */
	public static final String STUDENT_LIFE_PREMIUM = "STUDENT_LIFE_PREMIUM";
	public static final String STUDENT_RECEIVABLE = "STUDENT_RECEIVABLE";
	public static final String STUDENT_AGENT_COMMISSION = "STUDENT_AGENT_COMMISSION";
	public static final String STUDENT_AGENT_PAYABLE = "STUDENT_AGENT_PAYABLE";
	public static final String STUDENT_SERVICE_CHARGES = "STUDENT_SERVICE_CHARGES";
	public static final String STUDENT_STAMP_FEE = "STUDENT_STAMP_FEE";
	public static final String STUDENT_LIFE_CLAIM = "STUDENT_LIFE_CLAIM";
	public static final String STUDENT_LIFE_PAYABLE = "STUDENT_LIFE_PAYABLE";
	public static final String STUDENT_MEDICAL_FEES = "STUDENT_MEDICAL_FEES";
	public static final String STUDENT_MEDICAL_FEES_PAYABLE = "STUDENT_MEDICAL_FEES_PAYABLE";
	
	/* Provision For Surrender(ZN 09282021)*/
	public static final String PROVISION_ACCOUNT_PREMIUM = "PROVISION_ACCOUNT_PREMIUM";
	public static final String PROVISION_PUBLIC_LIFE_PREMIUM = "PROVISION_PUBLIC_LIFE_PREMIUM";
	public static final String PROVISION_SHORTTERM_LIFE_PREMIUM = "PROVISION_SHORTTERM_LIFE_PREMIUM";
	public static final String PROVISION_STUDENT_LIFE_PREMIUM = "PROVISION_STUDENT_LIFE_PREMIUM";
	public static final String PROVISION_SMART_SAVING_LIFE_PREMIUM = "PROVISION_SMART_SAVING_LIFE_PREMIUM";
	
	public static final String PUBLIC_TERM_LIFE_PREMIUM = "PUBLIC_TERM_LIFE_PREMIUM";
	public static final String PUBLIC_TERM_LIFE_RECEIVABLE = "PUBLIC_TERM_LIFE_RECEIVABLE";
	public static final String PUBLIC_TERM_LIFE_AGENT_COMMISSION = "PUBLIC_TERM_LIFE_AGENT_COMMISSION";
	public static final String PUBLIC_TERM_LIFE_AGENT_PAYABLE = "PUBLIC_TERM_LIFE_AGENT_PAYABLE";
	public static final String PUBLIC_TERM_LIFE_SERVICE_CHARGES = "PUBLIC_TERM_LIFE_SERVICE_CHARGES";
	public static final String PUBLIC_TERM_LIFE_STAMP_FEE = "PUBLIC_TERM_LIFE_STAMP_FEE";
	public static final String PUBLIC_TERM_LIFE_CLAIM = "PUBLIC_TERM_LIFE_CLAIM";
	public static final String PUBLIC_TERM_LIFE_PAYABLE = "PUBLIC_TERM_LIFE_PAYABLE";
	public static final String PUBLIC_TERM_LIFE_MEDICAL_FEES = "PUBLIC_TERM_LIFE_MEDICAL_FEES";
	public static final String PUBLIC_TERM_LIFE_MEDICAL_FEES_PAYABLE = "PUBLIC_TERM_LIFE_MEDICAL_FEES_PAYABLE";

	public static final String SHORT_ENDOWMENT_SUNDRY = "SHORT_ENDOWMENT_SUNDRY";

	/* Farmer */
	public static final String FARMER_PREMIUM = "FARMER_PREMIUM";
	public static final String FARMER_RECEIVABLE = "FARMER_RECEIVABLE";
	public static final String FARMER_AGENT_COMMISSION = "FARMER_AGENT_COMMISSION";
	public static final String FARMER_AGENT_PAYABLE = "FARMER_AGENT_PAYABLE";
	public static final String FARMER_SERVICE_CHARGES = "FARMER_SERVICE_CHARGES";
	public static final String FARMER_STAMP_FEE = "FARMER_STAMP_FEE";
	public static final String FARMER_MEDICAL_FEES = "FARMER_MEDICAL_FEES";

	/* Personal Accident */
	public static final String PA_PREMIUM = "PA_PREMIUM";
	public static final String PA_RECEIVABLE = "PA_RECEIVABLE";
	public static final String PA_AGENT_COMMISSION = "PA_AGENT_COMMISSION";
	public static final String PA_AGENT_PAYABLE = "PA_AGENT_PAYABLE";
	public static final String PA_SERVICE_CHARGES = "PA_SERVICE_CHARGES";
	public static final String PA_STAMP_FEES = "PA_STAMP_FEES";
	public static final String PA_CLAIM = "PA_CLAIM";
	public static final String PA_PAYABLE = "PA_PAYABLE";
	public static final String PA_MEDICAL_FEES = "PA_MEDICAL_FEES";
	public static final String PA_MEDICAL_FEES_PAYABLE = "PA_MEDICAL_FEES_PAYABLE";

	/* Snake Bite */
	public static final String SNAKE_BITE_PREMIUM = "SNAKE_BITE_PREMIUM";
	public static final String SNAKE_BITE_RECEIVABLE = "SNAKE_BITE_RECEIVABLE";
	public static final String SNAKE_BITE_AGENT_COMMISSION = "SNAKE_BITE_AGENT_COMMISSION";
	public static final String SNAKE_BITE_AGENT_PAYABLE = "SNAKE_BITE_AGENT_PAYABLE";
	public static final String SNAKE_BITE_SERVICE_CHARGES = "SNAKE_BITE_SERVICE_CHARGES";
	public static final String SNAKE_BITE_STAMP_FEES = "SNAKE_BITE_STAMP_FEES";
	public static final String SNAKE_BITE_CLAIM = "SNAKE_BITE_CLAIM";
	public static final String SNAKE_BITE_PAYABLE = "SNAKE_BITE_PAYABLE";
	public static final String SNAKE_BITE_MEDICAL_FEES = "SNAKE_BITE_MEDICAL_FEES";
	public static final String SNAKE_BITE_MEDICAL_FEES_PAYABLE = "SNAKE_BITE_MEDICAL_FEES_PAYABLE";

	/* Group Life */
	public static final String GROUP_LIFE_PREMIUM = "GROUP_LIFE_PREMIUM";
	public static final String GROUP_LIFE_RECEIVABLE = "GROUP_LIFE_RECEIVABLE";
	public static final String GROUP_LIFE_AGENT_COMMISSION = "GROUP_LIFE_AGENT_COMMISSION";
	public static final String GROUP_LIFE_AGENT_PAYABLE = "GROUP_LIFE_AGENT_PAYABLE";
	public static final String GROUP_LIFE_SERVICE_CHARGES = "GROUP_LIFE_SERVICE_CHARGES";
	public static final String GROUP_LIFE_STAMP_FEES = "GROUP_LIFE_STAMP_FEES";
	public static final String GROUP_LIFE_CLAIM = "GROUP_LIFE_CLAIM";
	public static final String GROUP_LIFE_PAYABLE = "GROUP_LIFE_PAYABLE";
	public static final String GROUP_LIFE_MEDICAL_FEES = "GROUP_LIFE_MEDICAL_FEES";
	public static final String GROUP_LIFE_MEDICAL_FEES_PAYABLE = "GROUP_LIFE_MEDICAL_FEES_PAYABLE";

	/* Sport Man */
	public static final String SPORT_MAN_PREMIUM = "SPORT_MAN_PREMIUM";
	public static final String SPORT_MAN_RECEIVABLE = "SPORT_MAN_RECEIVABLE";
	public static final String SPORT_MAN_AGENT_COMMISSION = "SPORT_MAN_AGENT_COMMISSION";
	public static final String SPORT_MAN_AGENT_PAYABLE = "SPORT_MAN_AGENT_PAYABLE";
	public static final String SPORT_MAN_SERVICE_CHARGES = "SPORT_MAN_SERVICE_CHARGES";
	public static final String SPORT_MAN_STAMP_FEES = "SPORT_MAN_STAMP_FEES";
	public static final String SPORT_MAN_CLAIM = "SPORT_MAN_CLAIM";
	public static final String SPORT_MAN_PAYABLE = "SPORT_MAN_PAYABLE";
	public static final String SPORT_MAN_MEDICAL_FEES = "SPORT_MAN_MEDICAL_FEES";
	public static final String SPORT_MAN_MEDICAL_FEES_PAYABLE = "SPORT_MAN_MEDICAL_FEES_PAYABLE";

	/* Health */
	public static final String HEALTH_PREMIUM = "HEALTH_PREMIUM";
	public static final String HEALTH_RECEIVABLE = "HEALTH_RECEIVABLE";
	public static final String HEALTH_AGENT_COMMISSION = "HEALTH_AGENTCOMMISSION";
	public static final String HEALTH_AGENT_PAYABLE = "HEALTH_AGENT_PAYABLE";
	public static final String HEALTHL_SERVICE_CHARGES = "HEALTHL_SERVICE_CHARGES";
	public static final String HEALTHL_STAMP_FEES = "HEALTHL_STAMP_FEES";

	public static final String HEALTH_INSURANCE_CLAIM = "HEALTH_CLAIM";

	/* Critical Illness */
	public static final String CRITICAL_ILLNESS_PREMIUM = "CRITICAL_ILLNESS_PREMIUM";
	public static final String CRITICAL_ILLNESS_RECEIVABLE = "CRITICAL_ILLNESS_RECEIVABLE";
	public static final String CRITICAL_ILLNESS_AGENT_COMMISSION = "CRITICAL_ILLNESS_AGENT_COMMISSION";
	public static final String CRITICAL_ILLNESS_AGENT_PAYABLE = "CRITICAL_ILLNESS_AGENT_PAYABLE";
	public static final String CRITICAL_ILLNESS_SERVICE_CHARGES = "CRITICAL_ILLNESS_SERVICE_CHARGES";
	public static final String CRITICAL_ILLNESS_STAMP_FEES = "CRITICAL_ILLNESS_STAMP_FEES";

	/* Micro Health */
	public static final String MICRO_HEALTH_PREMIUM = "MICRO_HEALTH_PREMIUM";
	public static final String MICRO_HEALTH_RECEIVABLE = "MICRO_HEALTH_RECEIVABLE";
	public static final String MICRO_HEALTH_AGENT_COMMISSION = "MICRO_HEALTH_AGENT_COMMISSION";
	public static final String MICRO_HEALTH_AGENT_PAYABLE = "MICRO_HEALTH_AGENT_PAYABLE";
	public static final String MICRO_HEALTH_SERVICE_CHARGES = "MICRO_HEALTH_SERVICE_CHARGES";
	public static final String MICRO_HEALTH_STAMP_FEES = "MICRO_HEALTH_STAMP_FEES";

}
