package org.ace.insurance.payment.enums;

public enum TlfCategory {
	PREMIUM_TLF, CO_PREMIUM_TLF, SERVICE_CHARGES_TLF, ADMINIS_FEE, STAMP_TLF, CO_COMMISION_TLF, AGENTCOMMISION_TLF, AGCOMMISSION_PAYMENT_TLF, RECEIVABLE_SP_TLF, MEDICAL_FEES_TLF, MEDICAL_FEES_PAYMENT_TLF, LIFE_CLAIM_TLF, PROVISION_FEES_TLF;

}
