USE [FNILP]
GO

/****** Object:  Table [dbo].[PROPOSAL_LIFE_MEDICAL_CUSTOMER_TEMP]    Script Date: 10-Aug-20 10:51:58 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PROPOSAL_LIFE_MEDICAL_CUSTOMER_TEMP](
	[ID] [varchar](255) NOT NULL,
	[ACTIVEPOLICY] [int] NULL,
	[ACTIVEDDATE] [datetime] NULL,
	[BANKACCOUNTNO] [varchar](255) NULL,
	[BIRTHMARK] [varchar](255) NULL,
	[CLOSEDPOLICY] [int] NULL,
	[DATEOFBIRTH] [datetime] NULL,
	[FATHERNAME] [varchar](255) NULL,
	[FULLIDNO] [varchar](255) NULL,
	[GENDER] [varchar](255) NULL,
	[HEIGHT] [float] NULL,
	[IDTYPE] [varchar](255) NULL,
	[INITIALID] [varchar](255) NULL,
	[LABOURNO] [varchar](255) NULL,
	[MARITALSTATUS] [varchar](255) NULL,
	[PASSPORTTYPE] [varchar](255) NULL,
	[PLACEOFBIRTH] [varchar](255) NULL,
	[SALARY] [varchar](255) NULL,
	[VERSION] [int] NULL,
	[WEIGHT] [float] NULL,
	[EMAIL] [varchar](255) NULL,
	[FAX] [varchar](255) NULL,
	[MOBILE] [varchar](255) NULL,
	[PHONE] [varchar](255) NULL,
	[FIRSTNAME] [varchar](255) NULL,
	[LASTNAME] [varchar](255) NULL,
	[MIDDLENAME] [varchar](255) NULL,
	[OFFICEADDRESS] [varchar](255) NULL,
	[OFFICETOWNSHIPID] [varchar](255) NULL,
	[PERMANENTADDRESS] [varchar](255) NULL,
	[PERMANENTTOWNSHIPID] [varchar](255) NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDUSERID] [varchar](255) NULL,
	[UPDATEDDATE] [datetime] NULL,
	[UPDATEDUSERID] [varchar](255) NULL,
	[RESIDENTADDRESS] [varchar](255) NULL,
	[RESIDENTTOWNSHIPID] [varchar](255) NULL,
	[BANKBRANCHID] [varchar](255) NULL,
	[BRANCHID] [varchar](255) NULL,
	[NATIONALITYID] [varchar](255) NULL,
	[INDURSTRYID] [varchar](255) NULL,
	[OCCUPATIONID] [varchar](255) NULL,
	[QUALIFICATIONID] [varchar](255) NULL,
	[RELIGIONID] [varchar](255) NULL,
	[isExisting] [bit] NULL,
	[STATUS] [bit] NULL,
	[REFERENCEID] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

------------------------------------------------------------------------------------------------------------
USE [FNILP]
GO

/****** Object:  Table [dbo].[PROPOSAL_LIFE_MEDICAL_TEMP]    Script Date: 10-Aug-20 10:50:07 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PROPOSAL_LIFE_MEDICAL_TEMP](
	[ID] [varchar](255) NOT NULL,
	[COMPLETE] [bit] NULL,
	[ISNONFINANCIALENDORSE] [bit] NULL,
	[PAYMENTTERM] [int] NULL,
	[PORTALID] [varchar](255) NULL,
	[PROPOSALNO] [varchar](255) NULL,
	[PROPOSALTYPE] [varchar](255) NULL,
	[SALECHANNELTYPE] [varchar](255) NULL,
	[SUBMITTEDDATE] [datetime] NULL,
	[VERSION] [int] NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDUSERID] [varchar](255) NULL,
	[UPDATEDDATE] [datetime] NULL,
	[UPDATEDUSERID] [varchar](255) NULL,
	[AGENTID] [varchar](255) NULL,
	[BRANCHID] [varchar](255) NULL,
	[CUSTOMERID] [varchar](255) NULL,
	[LIFEPOLICYID] [varchar](255) NULL,
	[ORGANIZATIONID] [varchar](255) NULL,
	[PAYMENTTYPEID] [varchar](255) NULL,
	[SALEBANKID] [varchar](255) NULL,
	[PROPOSALSTATUS] [varchar](20) NULL,
	[SPECIALDISCOUNT] [float] NULL,
	[PERIODOFMONTH] [int] NULL,
	[STARTDATE] [datetime] NULL,
	[ENDDATE] [datetime] NULL,
	[CURRENCYRATE] [float] NULL,
	[SALESPOINTSID] [varchar](255) NULL,
	[CUSTOMERCLSOFHEALTH] [varchar](36) NULL,
	[ISSKIPPAYMENTTLF] [bit] NULL,
	[STATUS] [bit] NULL,
	[INFORMDATE] [datetime] NULL,
	[CUSTOMERTYPE] [varchar](255) NULL,
	[OLDMEDICALPOLICYID] [varchar](255) NULL,
	[SALEMANID] [varchar](255) NULL,
	[HEALTHTYPE] [varchar](50) NULL,
	[RATE] [float] NULL,
	[TOTALNCBAMOUNT] [float] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PROPOSAL_LIFE_MEDICAL_TEMP]  WITH CHECK ADD  CONSTRAINT [FK_PROPOSAL_CUSTOMER_TEMP] FOREIGN KEY([CUSTOMERID])
REFERENCES [dbo].[PROPOSAL_LIFE_MEDICAL_CUSTOMER_TEMP] ([ID])
GO

ALTER TABLE [dbo].[PROPOSAL_LIFE_MEDICAL_TEMP] CHECK CONSTRAINT [FK_PROPOSAL_CUSTOMER_TEMP]
GO

------------------------------------------------------------------------------------------------------------
USE [FNILP]
GO

/****** Object:  Table [dbo].[PROPOSAL_LIFE_MEDICAL_INSUREDPERSON_TEMP]    Script Date: 10-Aug-20 10:55:30 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PROPOSAL_LIFE_MEDICAL_INSUREDPERSON_TEMP](
	[ID] [varchar](255) NOT NULL,
	[ADDONTERMPREMIUM] [float] NULL,
	[AGE] [int] NULL,
	[APPROVED] [bit] NULL,
	[APPROVEDSUMINSURED] [float] NULL,
	[BASICTERMPREMIUM] [float] NULL,
	[CLSOFHEALTH] [varchar](255) NULL,
	[DATEOFBIRTH] [datetime] NULL,
	[ENDORSEMENTNETADDONPREMIUM] [float] NULL,
	[ENDORSEMENTNETBASICPREMIUM] [float] NULL,
	[ENDORSEMENTSTATUS] [varchar](255) NULL,
	[FATHERNAME] [varchar](255) NULL,
	[GENDER] [varchar](255) NULL,
	[IDNO] [varchar](255) NULL,
	[IDTYPE] [varchar](255) NULL,
	[INPERSONGROUPCODENO] [varchar](255) NULL,
	[INITIALID] [varchar](255) NULL,
	[INPERSONCODENO] [varchar](255) NULL,
	[INTEREST] [float] NULL,
	[NEEDMEDICALCHECKUP] [bit] NULL,
	[proposedPremium] [float] NULL,
	[PROPOSEDSUMINSURED] [float] NULL,
	[REJECTREASON] [varchar](255) NULL,
	[UNIT] [int] NULL,
	[VERSION] [int] NULL,
	[FIRSTNAME] [varchar](255) NULL,
	[LASTNAME] [varchar](255) NULL,
	[MIDDLENAME] [varchar](255) NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDUSERID] [varchar](255) NULL,
	[UPDATEDDATE] [datetime] NULL,
	[UPDATEDUSERID] [varchar](255) NULL,
	[RESIDENTADDRESS] [varchar](255) NULL,
	[RESIDENTTOWNSHIPID] [varchar](255) NULL,
	[LIFEPROPOSALID] [varchar](255) NULL,
	[CUSTOMERID] [varchar](255) NULL,
	[OCCUPATIONID] [varchar](255) NULL,
	[PRODUCTID] [varchar](255) NULL,
	[TYPESOFSPORTID] [varchar](255) NULL,
	[RELATIONSHIPID] [char](36) NULL,
	[APPROVEDUNIT] [int] NULL,
	[weight] [int] NULL,
	[HEIGHT] [int] NULL,
	[PREMIUMRATE] [numeric](18, 4) NULL,
	[RISKYOCCUPATIONID] [varchar](255) NULL,
	[PHONE] [varchar](50) NULL,
	[PARENTDOB] [datetime] NULL,
	[GRATEINFOID] [varchar](36) NULL,
	[PARENTNAME] [varchar](50) NULL,
	[PARENTIDNO] [varchar](50) NULL,
	[PARENTIDTYPE] [varchar](20) NULL,
	[SCHOOLID] [varchar](36) NULL,
	[ISPAIDPREMIUMFORPAIDUP] [bit] NULL,
	[PREMIUM] [float] NULL,
	[SAMECUSTOMER] [bit] NULL,
	[GUARDIANID] [varchar](255) NULL,
	[MEDICALPROPOSALID] [varchar](255) NULL,
	[SUMINSURED] [float] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PROPOSAL_LIFE_MEDICAL_INSUREDPERSON_TEMP] ADD  DEFAULT ((0)) FOR [ISPAIDPREMIUMFORPAIDUP]
GO

ALTER TABLE [dbo].[PROPOSAL_LIFE_MEDICAL_INSUREDPERSON_TEMP] ADD  DEFAULT ((0)) FOR [SAMECUSTOMER]
GO

ALTER TABLE [dbo].[PROPOSAL_LIFE_MEDICAL_INSUREDPERSON_TEMP]  WITH CHECK ADD  CONSTRAINT [FK_INSUREDPERSON_CUSTOMER_TEMP] FOREIGN KEY([CUSTOMERID])
REFERENCES [dbo].[PROPOSAL_LIFE_MEDICAL_CUSTOMER_TEMP] ([ID])
GO

ALTER TABLE [dbo].[PROPOSAL_LIFE_MEDICAL_INSUREDPERSON_TEMP] CHECK CONSTRAINT [FK_INSUREDPERSON_CUSTOMER_TEMP]
GO

ALTER TABLE [dbo].[PROPOSAL_LIFE_MEDICAL_INSUREDPERSON_TEMP]  WITH CHECK ADD  CONSTRAINT [FK_LIFEMEDICAL_INSUREDPERSON_TEMP] FOREIGN KEY([LIFEPROPOSALID])
REFERENCES [dbo].[PROPOSAL_LIFE_MEDICAL_TEMP] ([ID])
GO

ALTER TABLE [dbo].[PROPOSAL_LIFE_MEDICAL_INSUREDPERSON_TEMP] CHECK CONSTRAINT [FK_LIFEMEDICAL_INSUREDPERSON_TEMP]
GO

------------------------------------------------------------------------------------------------------------
USE [FNILP]
GO

/****** Object:  Table [dbo].[PROPOSAL_LIFE_MEDICAL_BENEFICIARIES_TEMP]    Script Date: 10-Aug-20 10:57:59 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PROPOSAL_LIFE_MEDICAL_BENEFICIARIES_TEMP](
	[ID] [varchar](255) NOT NULL,
	[AGE] [int] NULL,
	[BENEFICIARYNO] [varchar](255) NULL,
	[GENDER] [varchar](255) NULL,
	[IDNO] [varchar](255) NULL,
	[IDTYPE] [varchar](255) NULL,
	[INITIALID] [varchar](255) NULL,
	[PERCENTAGE] [real] NULL,
	[VERSION] [int] NULL,
	[FIRSTNAME] [varchar](255) NULL,
	[LASTNAME] [varchar](255) NULL,
	[MIDDLENAME] [varchar](255) NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDUSERID] [varchar](255) NULL,
	[UPDATEDDATE] [datetime] NULL,
	[UPDATEDUSERID] [varchar](255) NULL,
	[RESIDENTADDRESS] [varchar](255) NULL,
	[RESIDENTTOWNSHIPID] [varchar](255) NULL,
	[INSUREDPERSONID] [varchar](255) NULL,
	[RELATIONSHIPID] [varchar](255) NULL,
	[PHONE] [varchar](50) NULL,
	[DATEOFBIRTH] [datetime] NULL,
	[FATHERNAME] [varchar](255) NULL,
	[EMAIL] [varchar](255) NULL,
	[FAX] [varchar](255) NULL,
	[MOBILE] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PROPOSAL_LIFE_MEDICAL_BENEFICIARIES_TEMP]  WITH CHECK ADD  CONSTRAINT [FK_INSUREDPERSON_BENE_TEMP] FOREIGN KEY([INSUREDPERSONID])
REFERENCES [dbo].[PROPOSAL_LIFE_MEDICAL_INSUREDPERSON_TEMP] ([ID])
GO

ALTER TABLE [dbo].[PROPOSAL_LIFE_MEDICAL_BENEFICIARIES_TEMP] CHECK CONSTRAINT [FK_INSUREDPERSON_BENE_TEMP]
GO

------------------------------------------------------------------------------------------------------------
USE [FNILP]
GO

/****** Object:  Table [dbo].[PROPOSAL_LIFE_MEDICAL_CUSTOMERFAMILY_TEMP]    Script Date: 10-Aug-20 10:59:44 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PROPOSAL_LIFE_MEDICAL_CUSTOMERFAMILY_TEMP](
	[DATEOFBIRTH] [datetime] NULL,
	[IDNO] [varchar](255) NULL,
	[IDTYPE] [varchar](255) NULL,
	[INITIALID] [varchar](255) NULL,
	[FIRSTNAME] [varchar](255) NULL,
	[LASTNAME] [varchar](255) NULL,
	[MIDDLENAME] [varchar](255) NULL,
	[INDUSTRYID] [varchar](255) NULL,
	[OCCUPATIONID] [varchar](255) NULL,
	[RELATIONSHIPID] [varchar](255) NULL,
	[CUSTOMERID] [varchar](255) NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PROPOSAL_LIFE_MEDICAL_CUSTOMERFAMILY_TEMP]  WITH CHECK ADD  CONSTRAINT [FK_CUSTOMERFAMILY_CUSTOMER_TEMP] FOREIGN KEY([CUSTOMERID])
REFERENCES [dbo].[PROPOSAL_LIFE_MEDICAL_CUSTOMER_TEMP] ([ID])
GO

ALTER TABLE [dbo].[PROPOSAL_LIFE_MEDICAL_CUSTOMERFAMILY_TEMP] CHECK CONSTRAINT [FK_CUSTOMERFAMILY_CUSTOMER_TEMP]
GO

------------------------------------------------------------------------------------------------------------
USE [FNILP]
GO

/****** Object:  Table [dbo].[PROPOSAL_LIFE_MEDICAL_CUSTOMERINFOSTATUS_TEMP]    Script Date: 10-Aug-20 11:00:39 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PROPOSAL_LIFE_MEDICAL_CUSTOMERINFOSTATUS_TEMP](
	[ID] [varchar](255) NOT NULL,
	[STATUSNAME] [varchar](255) NULL,
	[VERSION] [int] NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDUSERID] [varchar](255) NULL,
	[UPDATEDDATE] [datetime] NULL,
	[UPDATEDUSERID] [varchar](255) NULL,
	[CUSTOMERID] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PROPOSAL_LIFE_MEDICAL_CUSTOMERINFOSTATUS_TEMP]  WITH CHECK ADD  CONSTRAINT [FK_CUSTOMERINFOSTATUS_CUSTOMER_TEMP] FOREIGN KEY([CUSTOMERID])
REFERENCES [dbo].[PROPOSAL_LIFE_MEDICAL_CUSTOMER_TEMP] ([ID])
GO

ALTER TABLE [dbo].[PROPOSAL_LIFE_MEDICAL_CUSTOMERINFOSTATUS_TEMP] CHECK CONSTRAINT [FK_CUSTOMERINFOSTATUS_CUSTOMER_TEMP]
GO

------------------------------------------------------------------------------------------------------------
USE [FNILP]
GO

/****** Object:  Table [dbo].[PROPOSAL_LIFE_MEDICAL_INSUREDPERSON_ADDON_TEMP]    Script Date: 10-Aug-20 11:01:36 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PROPOSAL_LIFE_MEDICAL_INSUREDPERSON_ADDON_TEMP](
	[ID] [varchar](255) NOT NULL,
	[PREMIUM] [float] NULL,
	[UNIT] [int] NULL,
	[VERSION] [int] NULL,
	[CREATEDDATE] [datetime] NULL,
	[CREATEDUSERID] [varchar](255) NULL,
	[UPDATEDDATE] [datetime] NULL,
	[UPDATEDUSERID] [varchar](255) NULL,
	[MEDIPROPOSALINSUREDPERSONID] [varchar](255) NULL,
	[MEDICALPRODUCTADDONID] [varchar](255) NULL,
	[SUMINSURED] [float] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO