package org.ace.java.web.common;

public class MessageId {
	/* Login */
	public static final String USER_NAME_FAIL = "USER_NAME_FAIL";
	public static final String USER_PASSWORD_FAIL = "USER_PASSWORD_FAIL";
	public static final String USER_BRANCH_FAIL = "USER_BRANCH_FAIL";

	// Common
	public static final String INVALID_NUMBER = "INVALID_NUMBER";
	public static final String SELECT_RESPONSIBLE_USER = "SELECT_RESPONSIBLE_USER";
	public static final String ATLEAST_ONE_RESPONSIBLE_USER = "ATLEAST_ONE_RESPONSIBLE_USER";
	public static final String USER_CHANGER_PROCESS_SUCCESS = "USER_CHANGER_PROCESS_SUCCESS";
	public static final String POLICYNOTFINISH = "POLICYNOTFINISH";

	/* Business Logic MessageId */
	public static final String EXISTING_CUSTOMER = "EXISTING_CUSTOMER";
	public static final String EXISTING_AGENT = "EXISTING_AGENT";
	public static final String EXISTING_CASHIER = "EXISTING_CASHIER";
	public static final String LOGIN_FAILED = "LOGIN_FAILED";
	public static final String INSERT_SUCCESS = "INSERT_SUCCESS";
	public static final String UPDATE_SUCCESS = "UPDATE_SUCCESS";
	public static final String DELETE_SUCCESS = "DELETE_SUCCESS";
	public static final String SAVE_SUCCESS = "SAVE_SUCCESS";
	public static final String NEED_TO_SELECT_ONE_RECORD = "NEED_TO_SELECT_ONE_RECORD";
	public static final String EXISTING_NRCNO = "EXISTING_NRCNO";
	public static final String CHILD_RECORD_FOUND = "CHILD_RECORD_FOUND";

	/* Co-insurance */
	public static final String PRODUCT_GROUP_PERCENT_CHECKED = "PRODUCT_GROUP_PERCENTAGE_CHECKED_SUCCESS";
	public static final String COINSURANCE_OUT_ADD_SUCCESS = "COINSURANCE_OUT_ADD_SUCCESS";
	public static final String COINSURANCE_OUT_ADD_FAIL = "COINSURANCE_OUT_ADD_FAIL";
	public static final String COINSURANCE_IN_ADD_SUCCESS = "COINSURANCE_IN_ADD_SUCCESS";
	public static final String COINSURANCE_IN_ADD_FAIL = "COINSURANCE_IN_ADD_FAIL";
	public static final String COINSURANCE_IN_UPDATE_SUCCESS = "COINSURANCE_IN_UPDATE_SUCCESS";
	public static final String COINSURANCE_IN_UPDATE_FAIL = "COINSURANCE_IN_UPDATE_FAIL";
	public static final String COINSURANCE_COMPANY_ADD_SUCCESS = "COINSURANCE_COMPANY_ADD_SUCCESS";
	public static final String COINSURANCE_COMPANY_ADD_FAIL = "COINSURANCE_COMPANY_ADD_FAIL";
	public static final String PRODUCT_GROUP_PERCENT_ERROR = "PRODUCT_GROUP_PERCENTAGE_CHECKED_ERROR";
	public static final String PRODUCT_GROUP_PERCENT_LESS_ERROR = "PRODUCT_GROUP_PERCENTAGE_LESS_ERROR";
	public static final String PRODUCT_GROUP_REQUIRED = "PRODUCT_GROUP_REQUIRED";
	public static final String INVALID_PERIOD = "INVALID_PERIOD";
	/* Change Password */
	public static final String OLD_PASSWORD_DOES_NOT_MATCH = "OLD_PASSWORD_DOES_NOT_MATCH";
	public static final String DOES_NOT_MATCH_CONFIRM_PASSWORD = "DOES_NOT_MATCH_CONFIRM_PASSWORD";
	public static final String SUCCESS_CHANGE_PASSWORD = "SUCCESS_CHANGE_PASSWORD";

	public final static String UNDERWRITING_PROCESS_SUCCESS = "UNDERWRITING_PROCESS_SUCCESS";
	public final static String UNDERWRITING_PROCESS_SUCCESS_PARAM = "UNDERWRITING_PROCESS_SUCCESS_PARAM";
	public final static String UNDERWRITING_PROPOSAL_INFO_MESSAGE = "UNDERWRITING_PROPOSAL_INFO_MESSAGE";
	public final static String UNDERWRITING_PREMIUM_CALCULATION_SUCCESS = "UNDERWRITING_PREMIUM_CALCULATION_SUCCESS";
	public final static String ENDORSEMENT_PREMIUM_CALCULATION_SUCCESS = "ENDORSEMENT_PREMIUM_CALCULATION_SUCCESS";
	public final static String ENDORSEMENTG_PROCESS_SUCCESS = "ENDORSEMENT_PROCESS_SUCCESS";
	public final static String POLICY_PROCESS_SUCCESS = "POLICY_PROCESS_SUCCESS";
	public final static String EDIT_PROPOSAL_PROCESS_SUCCESS = "EDIT_PROPOSAL_PROCESS_SUCCESS";
	public final static String EDIT_PROPOSAL_PROCESS_SUCCESS_PARAM = "EDIT_PROPOSAL_PROCESS_SUCCESS_PARAM";
	public final static String SURVEY_PROCESS_SUCCESS = "SURVEY_PROCESS_SUCCESS";
	public final static String ATTACHMENT_PROCESS_SUCCESS = "ATTACHMENT_PROCESS_SUCCESS";
	public final static String APPROVAL_PROCESS_SUCCESS = "APPROVAL_PROCESS_SUCCESS";
	public final static String AUTHORIZE_PROCESS_SUCCESS = "AUTHORIZE_PROCESS_SUCCESS";
	public final static String REDIRECT_PROCESS_SUCCESS = "REDIRECT_PROCESS_SUCCESS";
	public final static String REJECT_PROPOSAL_PROCESS_SUCCESS = "REJECT_PROPOSAL_PROCESS_SUCCESS";
	public final static String CONFIRMATION_PROCESS_SUCCESS = "CONFIRMATION_PROCESS_SUCCESS";
	public final static String CONFIRMATION_PROCESS_SUCCESS_PARAM = "CONFIRMATION_PROCESS_SUCCESS_PARAM";
	public final static String PAYMENT_PROCESS_SUCCESS = "PAYMENT_PROCESS_SUCCESS";
	public final static String PAYMENT_ORDER_PROCESS_SUCCESS = "PAYMENT_ORDER_PROCESS_SUCCESS";
	public final static String ISSUING_PROCESS_SUCCESS = "ISSUING_PROCESS_SUCCESS";
	public final static String ISSUING_PROCESS_SUCCESS_PARAM = "ISSUING_PROCESS_SUCCESS_PARAM";
	public final static String INFORM_PROCESS_SUCCESS = "INFORM_PROCESS_SUCCESS";
	public final static String INFORM_PROCESS_SUCCESS_PARAM = "INFORM_PROCESS_SUCCESS_PARAM";
	public final static String RENEWAL_INFORM_PROCESS_SUCCESS = "RENEWAL_INFORM_PROCESS_SUCCESS";
	public final static String AGENT_COMMISSION_INVOICE_SUCCESS = "AGENT_COMMISSION_INVOICE_SUCCESS";
	public final static String CLAIM_MEDICAL_INVOICE_SUCCESS = "CLAIM_MEDICAL_INVOICE_SUCCESS";
	public final static String CLAIM_MEDICAL_SANCTION_SUCCESS = "CLAIM_MEDICAL_SANCTION_SUCCESS";

	public final static String PRINTSETUP_PROCESS_SUCCESS = "PRINTSETUP_PROCESS_SUCCESS";
	public final static String RENEWAL_PROCESS_SUCCESS = "RENEWAL_PROCESS_SUCCESS";
	public final static String RENEWAL_PROCESS_SUCCESS_PARAM = "RENEWAL_PROCESS_SUCCESS_PARAM";
	public final static String UNDERWRITING_PREMIUM_CALCULATION_FAIL = "UNDERWRITING_PREMIUM_CALCULATION_FAIL";
	public final static String ENDORSEMENT_PREMIUM_CALCULATION_FAIL = "ENDORSEMENT_PREMIUM_CALCULATION_FAIL";

	public final static String REQUIRED_COUNTRY = "REQUIRED_COUNTRY";
	public final static String REQUIRED_CURRENCY = "REQUIRED_CURRENCY";
	public final static String REQUIRED_TOWNSHIP = "REQUIRED_TOWNSHIP";
	public final static String REQUIRED_CLASSOFINSURANCE = "REQUIRED_CLASSOFINSURANCE";
	public final static String REQUIRED_CITY = "REQUIRED_CITY";
	public final static String REQUIRED_PROVINCE = "REQUIRED_PROVINCE";
	public final static String REQUIRED_ADDON = "REQUIRED_ADDON";
	public final static String REQUIRED_ADDONTYPE = "REQUIRED_ADDONTYPE";
	public final static String REQUIRED_BRANCH = "REQUIRED_BRANCH";
	public final static String REQUIRED_IDTYPE = "REQUIRED_IDTYPE";
	public final static String REQUIRED_GENDER = "REQUIRED_GENDER";
	public final static String REQUIRED_NATIONALITY = "REQUIRED_NATIONALITY";
	public final static String REQUIRED_RESIDENTTOWNSHIP = "REQUIRED_RESIDENTTOWNSHIP";
	public final static String REQUIRED_BANK = "REQUIRED_BANK";
	public final static String REQUIRED_PAYMENTTYPE = "REQUIRED_PAYMENTTYPE";
	public final static String REQUIRED_REFERRAL = "REQUIRED_REFERRAL";
	public final static String REQUIRED_CUSTOMER = "REQUIRED_CUSTOMER";
	public final static String REQUIRED_SALEMAN_OR_AGENT = "REQUIRED_SALEMAN_OR_AGENT";
	public final static String REQUIRED_TYPEOFBODY = "REQUIRED_TYPEOFBODY";
	public final static String REQUIRED_COMPANY = "REQUIRED_COMPANY";
	public final static String REQUIRED_MANUFACTURE = "REQUIRED_MANUFACTURE";
	public final static String REQUIRED_RELATIONSHIP = "REQUIRED_RELATIONSHIP";
	public static final String REQUIRED_QUALIFICATION = "REQUIRED_QUALIFICATION";
	public static final String REQUIRED_RELIGION = "REQUIRED_RELIGION";
	public static final String REQUIRED_PARMANENTTOWNSHIP = "REQUIRED_PARMANENTTOWNSHIP";
	public static final String REQUIRED_OCCUPATION = "REQUIRED_OCCUPATION";
	public static final String REQUIRED_INDUSTRY = "REQUIRED_INDUSTRY";
	public static final String REQUIRED_OFFICETOWNSHIP = "REQUIRED_OFFICETOWNSHIP";
	public static final String REQUIRED_VEHICLE = "REQUIRED_VEHICLE";
	public static final String INVALID_VEHICLE = "INVALID_VEHICLE_PARAM";
	public static final String INVALID_VEHICLE_LIST = "INVALID_VEHICLE_LIST";
	public static final String YOU_CAN_INSURE_ONLY_ONE_VEHICLE = "YOU_CAN_INSURE_ONLY_ONE_VEHICLE";
	public static final String REQUIRED_AT_LEAST_10_VEHICLES = "REQUIRED_AT_LEAST_10_VEHICLES";
	public static final String REQUIRED_KEYFACTOR_CONFIG = "REQUIRED_KEYFACTOR_CONFIG";
	public static final String REQUIRED_DRIVER = "REQUIRED_DRIVER";
	public static final String NO_RECORDS_FOUND = "NO_RECORDS_FOUND";
	public static final String SET_CASH_QUANTITY = "SET_CASH_QUANTITY";
	public static final String REQUIRED_VALUES = "REQUIRED_VALUES";
	public static final String REQUIRED_ENDORSEMENT_STATUS = "REQUIRED_ENDORSEMENT_STATUS";
	public static final String ENDORSEMENT_STATUS_ERROR = "ENDORSEMENT_STATUS_ERROR";
	public static final String MIN_PERIOD_MSG = "MIN_PERIOD_MSG";
	public static final String MAX_PERIOD_MSG = "MAX_PERIOD_MSG";
	public static final String MIN_UNIT_MSG = "MIN_UNIT_MSG";
	public static final String MAX_UNIT_MSG = "MAX_UNIT_MSG";
	public static final String MIN_SI_MSG = "MIN_SI_MSG";
	public static final String MAX_SI_MSG = "MAX_SI_MSG";

	/* Motor Proposal */
	public static final String REQUIRED_LOADING_OR_SEATING = "REQUIRED_LOADING_OR_SEATING";
	public static final String INVALID_PROPOSED_ADDON_SUMINSURED = "INVALID_PROPOSED_ADDON_SUMINSURED";
	public static final String INVALID_PRODUCTGROUP = "INVALID_PRODUCTGROUP";
	public static final String INVALID_PERIOD_OF_VECHICLE = "INVALID_PERIOD_OF_VECHICLE";
	public static final String DENY_PROCESS_OK = "DENY_PROCESS_OK";
	public static final String INVALID_PERIOD_OF_VEHICLE_EXTEND = "INVALID_PERIOD_OF_VEHICLE_EXTEND";
	public static final String INVALID_DATE = "INVALID_DATE";
	public static final String GREATER_THAN_CURRENTYEAR = "GREATER_THAN_CURRENTYEAR";
	public static final String EXISTING_TRAILERNO = "EXISTING_TRAILERNO";
	public static final String ONLY_ONE_VEHICLE_CAN_INSURED = "ONLY_ONE_VEHICLE_CAN_INSURED";

	public static final String REG_EXISTING = "REG_EXISTING";
	public static final String INVALID_REGISTRATIOIN = "REG_EXISTING";
	public static final String REG_EXISTING_RANGE = "REG_EXISTING_RANGE";
	public static final String REG_TERMINATE_INSURER = "REG_TERMINATE_INSURER";
	public static final String REG_TERMINATE_RENEWAL = "REG_TERMINATE_RENEWAL";
	public static final String VEHICLE_NO_PREMIUM_RATE = "VEHICLE_NO_PREMIUM_RATE";

	/* Fire Proposal */
	public static final String REQUIRED_BUILDING = "REQUIRED_BUILDING";
	public static final String REQUIRED_BUILDING_CLASS = "REQUIRED_BUILDING_CLASS";
	public static final String REQUIRED_FLOOR = "REQUIRED_FLOOR";
	public static final String REQUIRED_WALL = "REQUIRED_WALL";
	public static final String REQUIRED_ROOF = "REQUIRED_ROOF";
	public static final String REQUIRED_MAINCOVER = "REQUIRED_MAINCOVER";
	public static final String SUMINSURED_MUSTBE_NUMBER = "SUMINSURED_MUSTBE_NUMBER";
	public static final String SHOULDNOTBEZERO = "SHOULDNOTBEZERO";
	public static final String INVALID_MAINCOVER_PERIOD = "INVALID_MAINCOVER_PERIOD";
	public static final String MAX_PERIOD_DAYS = "MAX_PERIOD_DAYS";
	public static final String MIN_PERIOD_DAYS = "MIN_PERIOD_DAYS";

	/* Life Proposal */
	public static final String OVER_BENEFICIARY_PERCENTAGE = "OVER_BENEFICIARY_PERCENTAGE";
	public static final String LOWER_BENEFICIARY_PERCENTAGE = "LOWER_BENEFICIARY_PERCENTAGE";
	public static final String REQUIRED_BENEFICIARY_PERSON = "REQUIRED_BENEFICIARY_PERSON";
	public static final String INVALID_BENEFICIARY_PERSON = "INVALID_BENEFICIARY_PERSON";
	public static final String REQUIRED_INSURED_PERSION = "REQUIRED_INSURED_PERSION";
	public static final String REQUIRED_GROUPLIFE_INSURED_PERSON = "REQUIRED_GROUPLIFE_INSURED_PERSON";
	public static final String MUSTBE_GROUPLIFE_INSURED_PERSON = "MUSTBE_GROUPLIFE_INSURED_PERSON";
	public static final String INVALID_INSURED_PERSON = "INVALID_INSURED_PERSON";
	public static final String MAXIMUM_INSURED_YEARS = "MAXIMUM_INSURED_YEARS";
	public static final String BMI_MAXIMUM_POUNDS_LIMATION = "BMI_MAXIMUM_POUNDS_LIMATION";
	public static final String MINIMUN_INSURED_PERSON_AGE = "MINIMUN_INSURED_PERSON_AGE";
	public static final String MINIMUN_INSURED_PERIOD = "MINIMUN_INSURED_PERIOD";
	public static final String AVAILABLE_INSURED_PERIOD = "AVAILABLE_INSURED_PERIOD";
	public static final String INVALID_SURVEY_DATE = "INVALID_SURVEY_DATE";
	public static final String INVALID_INSUREDPERSON_NAME = "INVALID_INSUREDPERSON_NAME";
	public static final String NEED_CLASSFICATION_HEALTH = "NEED_CLASSFICATION_HEALTH";
	public static final String INSUREDPERSON_CANNOT_BE_SAME_PERSON = "INSUREDPERSON_CANNOT_BE_SAME_PERSON";
	public static final String PRODUCT_CANNOT_BE_CHANGE = "PRODUCT_CANNOT_BE_CHANGE";
	public static final String BENEFICIARY_PERCENTAGE = "BENEFICIARY_PERCENTAGE";
	public static final String INVALID_PERIOD_YEAR = "INVALID_PERIOD_YEAR";
	public static final String AVAILABLE_SI_AMOUNT = "AVAILABLE_SI_AMOUNT";
	public static final String MINIMUM_SI_AMOUNT = "MINIMUM_SI_AMOUNT";

	/* Life policy */
	public static final String EDIT_POLICY_PROCESS = "SUCCESS_EDIT_POLICY_PROCESS";
	public static final String SUCCESS_SPORTMANTRAVELABROAD_PROCESS = "SUCCESS_SPORTMANTRAVELABROAD_PROCESS";

	public final static String ALREADY_ADD_SCHOOL = "ALREADY_ADD_SCHOOL";

	public final static String ALREADY_ADD_GRADE = "ALREADY_ADD_GRADE";

	/* Renewal */
	public static final String EDIT_POLICY_RENEWAL_PROCESS_SUCCESS = "EDIT_POLICY_RENEWAL_PROCESS_SUCCESS";

	/* WorkFlow */
	public static final String WORKFLOW_INFORMATION_MESSAGE = "WORKFLOW_INFORMATION_MESSAGE";
	public final static String WORKFLOW_CHANGER_PROCESS_SUCCESS = "WORKFLOW_CHANGER_PROCESS_SUCCESS";
	/* fire Cliam */
	public static final String READYTOCLAIM = "READY_TO_CLAIM";
	public static final String NEEDSOMETHING = "NEED_SOMETHING_TO_PROVIDE";
	public static final String CANNOTFINDPOLICY = "CANNOT_FIND_POLICY";
	public static final String NOTREADYFORCLAIMAPPLY = "NOT_READY_FOR_CLAIM_APPLY";
	public static final String SUCCESS_FIRE_CLAIM_CLOSE = "SUCCESS_FIRE_CLAIM_CLOSE";
	public static final String SUCCESS_CLAIM_CO_SHARE = "SUCCESS_CLAIM_CO_SHARE";
	public static final String INVOICEVALUE_APPROVED_STATUS = "INVOICEVALUE_APPROVED_STATUS";
	public static final String INVOICEVALUE_REOPEN_STATUS = "INVOICEVALUE_REOPEN_STATUS";
	public static final String INVOICEVALUE_SHOULD_NOT_BE_GREATER_THAN_APPROVEDVALUE = "INVOICEVALUE_SHOULD_NOT_BE_GREATER_THAN_APPROVEDVALUE";

	/* FinancialReport */
	public static final String FINANCIAL_REPROT_YEAR_MESSAGE = "FINANCIAL_REPROT_YEAR_MESSAGE";
	public static final String POLICY_TYPE_INVALID = "POLICY_TYPE_INVALID";

	/* Life Claim */
	public static final String POLICY_NUMBER_NOT_EXIST = "POLICY_NUMBER_NOT_EXIST";
	public static final String RECEIPT_NUMBER_NOT_EXIST = "RECEIPT_NUMBER_NOT_EXIST";
	public static final String DISABILITY_REASON_REQUIRED = "DISABILITY_REASON_REQUIRED";
	public static final String DISABILITY_DATE_REQUIRED = "DISABILITY_DATE_REQUIRED";
	public static final String REQUIRED_RESPONSIBLE_PERSON = "REQUIRED_RESPONSIBLE_PERSON";
	public static final String REQUIRED_BENEFICIARY_PERSON_CHECKBOX = "REQUIRED_BENEFICIARY_PERSON_CHECKBOX";
	public static final String REQUIRED_SALEMAN = "REQUIRED_SALEMAN";
	public static final String REQUIRED_SUBMITTEDDATE = "REQUIRED_SUBMITTEDDATE";
	public static final String REQUIRED_DEATH_PERSONINFO = "REQUIRED_DEATH_PERSONINFO";
	public static final String REQUIRED_DISABILITY_PERSONINFO = "REQUIRED_DISABILITY_PERSONINFO";
	public static final String REQUIRED_DISABILITY_PERCENTAGE = "REQUIRED_DISABILITY_PERCENTAGE";
	public static final String CAUSE_OF_DISABILITY_IS_REQUIRED = "CAUSE_OF_DISABILITY_IS_REQUIRED";
	public static final String CAUSE_OF_PROPOSE_IS_REQUIRED = "CAUSE_OF_PROPOSE_IS_REQUIRED";
	public static final String MAXIMUM_DISABILITY_PERCENTAGE = "MAXIMUM_DISABILITY_PERCENTAGE";

	public final static String CLAIM_PROPOSAL_SUCCESS = "CLAIM_PROPOSAL_SUCCESS";

	/* Motor Claim */
	public static final String REQUIRED_DAMAGED_PART = "REQUIRED_DAMAGED_PART";
	public static final String INVALID_INCIDENT_DATE = "INVALID_INCIDENT_DATE";
	public static final String OUTORRANGE_INCIDENT_DATE = "OUTORRANGE_INCIDENT_DATE";
	public static final String INVALID_MOTORCLAIM = "INVALID_MOTORCLAIM";
	public static final String INVALID_PROPOSAL_DATE = "INVALID_PROPOSAL_DATE";
	public static final String REQUIRED_CAUSE_OF_INCIDENT = "REQUIRED_CAUSE_OF_INCIDENT";
	public static final String REQUIRED_ADDRESS_OF_INCIDENT = "REQUIRED_ADDRESS_OF_INCIDENT";
	public static final String REQUIRED_NOTIFICATION_DATE = "REQUIRED_NOTIFICATION_DATE";
	public static final String REQUIRED_PART_NAME = "REQUIRED_PART_NAME";
	public static final String REQUIRED__QUANTITY = "REQUIRED__QUANTITY";
	public static final String REQUIRED_ESTIMATED_VALUE = "REQUIRED_ESTIMATED_VALUE";
	public static final String REINSTATEMENT_PROCESS_SUCCESS = "REINSTATEMENT_PROCESS_SUCCESS";
	public static final String REQUIRED_INVOICE_VALUE = "REQUIRED_INVOICE_VALUE";
	public static final String REQUIRED_APPROVED_VALUE = "REQUIRED_APPROVED_VALUE";
	public static final String INVOICE_VALUE_GREATER_THAN_APPROVE = "INVOICE_VALUE_GREATER_THAN_APPROVE";
	public static final String EMPTY_REINSTATEMENT_ITEM = "EMPTY_REINSTATEMENT_ITEM";
	public static final String REQUIRED_SURVEY_VALUE = "REQUIRED_SURVEY_VALUE";

	/* Cash In Safe Claim */
	public static final String DATE_SHOULDBE_EQUAL_OR_BEFORE_DATE = "DATE_SHOULDBE_EQUAL_OR_BEFORE_DATE";

	/* Life Payment Bill Collection */
	public static final String ATLEAST_ONE_REQUIRED = "ATLEAST_ONE_REQUIRED";
	public static final String STARTDATE_MUSTBE_LESSTHAN_ENDDATE = "STARTDATE_MUSTBE_LESSTHAN_ENDDATE";
	public static final String ATLEAST_ONE_CHECK_REQUIRED = "ATLEAST_ONE_CHECK_REQUIRED";
	public static final String PAYMENTTIMES_GRT_ONE = "PAYMENTTIMES_GRT_ONE";
	public static final String PAYMENTTIMES_BIGGER_ERROR = "PAYMENTTIMES_BIGGER_ERROR";

	/* Agent Sanction */
	public static final String AGENT_SANCTION = "AGENT_SANCTION";
	public static final String ATLEAST_ONE_AGENTCOMMISSION = "ATLEAST_ONE_AGENTCOMMISSION";

	public static final String PLEASE_SELECT_POLICY_CRITERIA = "PLEASE_SELECT_POLICY_CRITERIA";
	public static final String CRITERIA_VALUE_REQUIRED = "CRITERIA_VALUE_REQUIRED";

	/* Travel Proposal */
	public static final String ALREADY_INSERT = "ALREADY_INSERT";
	public static final String VALID_NOOFPASSENGER = "VALID_NO_OF_PASSENGER";
	public static final String VALID_NOOFUNIT = "VALID_NO_OF_UNIT";

	/* Person Travel Proposal */
	public static final String REQUIRED_PRODUCT = "REQUIRED_PRODUCT";
	public static final String INVALID_UNIT = "INVALID_UNIT";
	public static final String INVALID_PASSENGER = "INVALID_PASSENGER";
	public static final String INVALID_START_END_DATE = "INVALID_START_END_DATE";
	public static final String INVALID_TOTALUNIT = "INVALID_TOTALUNIT";
	public static final String INVALID_TRAVELLER_UINT = "INVALID_TRAVELLER_UINT";
	public static final String OVER_TOTAL_UNIT = "OVER_TOTAL_UNIT";
	public static final String INVALID_PERSONTRAVELLER_UNIT = "INVALID_PERSONTRAVELLER_UNIT";

	/* Report Config */
	public static final String REPORT_CONFIG_SUCCESS = "REPORT_CONFIG_SUCCESS";
	public static final String JOB_IS_ALREADY_RUNNING = "JOB_IS_ALREADY_RUNNING";

	/* Motor Claim */
	public static final String INVALID_HOSPITAL_STARTDATE = "INVALID_HOSPITAL_STARTDATE";
	public static final String INVALID_HOSPITAL_ENDDATE = "INVALID_HOSPITAL_ENDDATE";
	public static final String SELECT_ONE_MOTORCLAIMITEM = "SELECT_ONE_MOTORCLAIMITEM";

	/* Survey Question */
	public static final String RESOURCE_QUESTION = "RESOURCE_QUESTION";
	public static final String QUESTION = "QUESTION";
	public static final String MINIMUM_PRIORITY_NUM = "MINIMUM_PRIORITY_NUM";
	public static final String MAXIMUM_PRIORITY_NUM = "MAXIMUM_PRIORITY_NUM";
	public static final String DUPLICATE_PRIORITY_NUM = "DUPLICATE_PRIORITY_NUM";

	/* Medical Hospitalized Claim */
	public static final String REQUIRED_HOSPITALIZEDPERSON_INFO = "REQUIRED_HOSPITALIZEDPERSON_INFO";
	/* Medical Hospitalized Claim for dashboad */
	public static final String MEDICAL_HOSP_ClAIM_PROCESS_SUCCESS_PARAM = "MEDICAL_HOSP_ClAIM_PROCESS_SUCCESS";

	/* for medical Death Claim */
	public static final String MEDICAL_ClAIM_PROCESS_SUCCESS = "MEDICAL_ClAIM_PROCESS_SUCCESS";
	public static final String MEDICAL_ClAIM_APPROVAL_PROCESS_SUCCESS = "MEDICAL_ClAIM_APPROVAL_PROCESS_SUCCESS";
	public static final String MEDICAL_ClAIM_INFORM_PROCESS_SUCCESS = "MEDICAL_ClAIM_INFORM_PROCESS_SUCCESS";
	public static final String REQUIRED_DEATHPERSON_INFO = "REQUIRED_DEATHPERSON_INFO";

	public static final String REQUIRED_BENEFICIRY_INFO = "REQUIRED_BENEFICIRY_INFO";
	/* for survey question */
	public static final String USE_SURVEYQUESTION_INFO = "USE_SURVEYQUESTION_INFO";

	/* for medical claim */
	public static final String NEED_REJECT_REASON = "NEED_REJECT_REASON";
	public static final String HOSPITALIZED_DATE_INFO = "HOSPITALIZED_DATE_INFO";
	public static final String OPERATION_DATE_INFO = "OPERATION_DATE_INFO";
	public static final String HOSPITALIZED_STARTDATE_INFO = "HOSPITALIZED_STARTDATE_INFO";
	public static final String HOSPITALIZED_ENDDATE_INFO = "HOSPITALIZED_ENDDATE_INFO";
	public static final String RECEIVED_DATE_INFO = "RECEIVED_DATE_INFO";
	public static final String VALUE_IS_REQUIRED = "VALUE_IS_REQUIRED";
	public static final String CLAIMTYPE_IS_REQUIRED = "CLAIMTYPE_IS_REQUIRED";

	public static final String ONLYONE_INPUT = "ONLYONE_INPUT";
	public static final String STARTDATE_AND_ENDDATE_INPUT = "STARTDATE_AND_ENDDATE_INPUT";
	public static final String NEED_REJECT_REASON_FILL = "NEED_REJECT_REASON_FILL";
	public static final String CLAIM_MESSAGE_WITHIN_ONEMONTH = "CLAIM_MESSAGE_WITHIN_ONEMONTH";
	public static final String MAXIMUM_INSURED_UNIT = "MAXIMUM_INSURED_UNIT";
	public static final String MEDICAL_INSURED_PERSON_MAXAGE = "MEDICAL_INSURED_PERSON_MAXAGE";
	public static final String MEDICAL_INSURED_PERSON_MINAGE = "MEDICAL_INSURED_PERSON_MINAGE";
	public static final String MAXIMUM_INSURED_PERSON_AGE = "MAXIMUM_INSURED_PERSON_AGE";

	/* for Medical Claim Initial Report */
	public static final String MEDICAL_ClAIM_INITIAL_REPORT_PROCESS_SUCCESS = "MEDICAL_ClAIM_INITIAL_REPORT_PROCESS_SUCCESS";

	/* for Medical propsal */
	public static final String NRC_FORMAT_INCORRECT = "NRC_FORMAT_INCORRECT";
	public static final String NRC_STATE_AND_TOWNSHIP_ERROR = "NRC_STATE_AND_TOWNSHIP_ERROR";
	public static final String MEDICAL_ClAIM_INITIAL_REPORT_PROCESS_UPDATE = "MEDICAL_ClAIM_INITIAL_REPORT_PROCESS_UPDATE";
	public static final String CUSTOMER_AGE_OVER_18 = "CUSTOMER_AGE_OVER_18";
	public static final String CUSTOMER_AGE_OVER_65 = "CUSTOMER_AGE_OVER_65";
	public static final String FILL_PHONE_NUMBER = "FILL_PHONE_NUMBER";
	public static final String HOSPITALIZE_REASONS = "HOSPITALIZE_REASONS";
	public static final String REQUIRE_BENEFICIARY = "REQUIRE_BENEFICIARY";
	public static final String REQUIRE_INSUREDPERSON = "REQUIRE_INSUREDPERSON";
	public static final String REQUIRE_TWO_INSUREDPERSON = "REQUIRE_TWO_INSUREDPERSON";
	public static final String INVALID_INDIVIDUAL_CUSTOMER = "INVALID_INDIVIDUAL_CUSTOMER";
	public static final String INVALID_CORPORATE_CUSTOMER = "INVALID_CORPORATE_CUSTOMER";
	public static final String ALREADY_ADD_INSUREDPERSON = "ALREADY_ADD_INSUREDPERSON";
	public static final String ALREADY_ADD_SELF_RELATION = "ALREADY_ADD_SELF_RELATION";
	public static final String REQUIRE_HISTORY_RECORD = "REQUIRE_HISTORY_RECORD";

	/* for Cargo propsal */
	public static final String REQUIRED_CARGO = "REQUIRED_CARGO";
	public static final String REQUIRED_SHIPVEHICLE_INFO = "REQUIRED_SHIPVEHICLE_INFO";
	public static final String HEADOFFICE = "Head Office";
	public static final String REQUIRED_ONLY_ONE_SHIPVEHICLE = "REQUIRED_ONLY_ONE_SHIPVEHICLE";

	/* for marine Hull propsal */
	public static final String REQUIRED_MARINEHULL_INFO = "REQUIRED_HULLINFO";

	/* for Mobile User */
	public static final String DOES_NOT_MATCH_PASSWORD = "DOES_NOT_MATCH_PASSWORD";

	/* for Agent Comparison Sales Report */
	public static final String REPORT_ERROR = "REPORT_ERROR";

	public static final String OVER_FIRE_DECLARATION_POLICY = "OVER_FIRE_DECLARATION_POLICY";
	public static final String BUILDING_DECLARATION_POLICY = "BUILDING_DECLARATION_POLICY";

	public static final String BUILDING_DECLARATION_POLICY_INVALID = "BUILDING_DECLARATION_POLICY_INVALID";
	public static final String BUILDING_DECLARATION_POLICY_ERROR = "BUILDING_DECLARATION_POLICY_ERROR";

	/* for Auto Renewal Process */
	public final static String AUTORENEWAL_PROCESS_SUCCESS = "AUTORENEWAL_PROCESS_SUCCESS";
	public final static String AUTORENEWAL_PROCESS_SUCCESS_PARAM = "AUTORENEWAL_PROCESS_SUCCESS_PARAM";

	/* for Claim Product */
	public static final String KEYFACTOR_REQUIRED = "KEYFACTOR_REQUIRED";
	public static final String CLIAIMPRODUCT_INSERT_SUCCESS = "CLIAIMPRODUCT_INSERT_SUCCESS_PARAM";
	public static final String CLIAIMPRODUCT_UPDATE_SUCCESS = "CLIAIMPRODUCT_UPDATE_SUCCESS_PARAM";

	/* Life Surrender Proposal */
	public static final String INVALID_LIFE_SURRENDER_PERIOD = "INVALID_LIFE_SURRENDER_PERIOD";
	public static final String INVALID_LIFE_SURRENDER_POLICY = "INVALID_LIFE_SURRENDER_POLICY";
	public static final String INVALID_LIFE_SURRENDER_AMOUNT = "INVALID_LIFE_SURRENDER_AMOUNT";
	public static final String INVALID_LIFE_SURRENDER_PROVISIONAMOUNT = "INVALID_LIFE_SURRENDER_PROVISION_AMOUNT";
	public static final String INVALID_LIFE_SURRENDER_PREINCOMEAMOUNT = "INVALID_LIFE_SURRENDER_PREINCOMEAMOUNT";

	/* Life PaidUp Proposal */
	public static final String INVALID_LIFE_PAIDUP_POLICY = "INVALID_LIFE_PAIDUP_POLICY";
	public static final String INVALID_LIFE_PAIDUP_PERIOD = "INVALID_LIFE_PAIDUP_PERIOD";
	public static final String PAYMENT_PROCESS_NOTCOMPLETE = "PAYMENT_PROCESS_NOTCOMPLETE";

	/* Medical Proposal */
	public static final String INVALID_ADDON_UNIT = "INVALID_ADDON_UNIT";

	public static final String INVALID_FARMER_UNIT = "INVALID_FARMER_UNIT";

	public static final String BASICPLUS_BALANCE = "BASICPLUS_BALANCE";

	public static final String MAX_BASICPLUS_UNIT = "MAX_BASICPLUS_UNIT";

	public static final String PA_MAX_INSURED_PERSON = "PA_MAX_INSURED_PERSON";

	public static final String REQUIRE_BASICPLUS_UNIT = "REQUIRE_BASICPLUS_UNIT";

	/* Tlf Import */
	public static final String IS_UPLOADED = "IS_UPLOADED";
	// For debugging and error log
	public static final String CSC_IMPORT_EXCEPTION = "CSC_IMPORT_EXCEPTION";
	public static final String CSC_FETCH = "CSC_FETCH";

	/* Overses Cargo */

	public static final String REQUIRED_OVERSEAS_VOYAGE_INFO = "REQUIRED_OVERSEAS_VOYAGE_INFO";

	/* Life Endorsement */
	public static final String PLEASE_SELECT_PRODUCT = "PLEASE_SELECT_PRODUCT";

	/* Coinsurance Ratio */
	public static final String REQUIRED_COINSURANCE_DETAIL_RATIO = "REQUIRED_COINSURANCE_DETAIL_RATIO";
	/* declarationYearEnd */
	public static final String DECLARATION_YEAR_END = "DECLARATION_YEAR_END";
	/* SnakeBitePolicy */
	public static final String CHOOSE_AT_LEAST_ONE_POLICY = "CHOOSE_AT_LEAST_ONE_POLICY";

	/* New Medical */
	public static final String REQUIRE_FIVE_INSUREDPERSON = "REQUIRE_FIVE_INSUREDPERSON";
	public static final String CUSTOMER_AGE_OVER = "CUSTOMER_AGE_OVER";
	public static final String BENEFICIARY_PERCENTAGE_MUST_BE_100 = "BENEFICIARY_PERCENTAGE_MUST_BE_100";
	public static final String REQUIRE_GUARDIAN = "REQUIRE_GUARDIAN";
	public static final String MAX_UNIT = "MAX_UNIT";
	public static final String CASH_RECEIPT_INFORMATION_MESSAGE = "CASH_RECEIPT_INFORMATION_MESSAGE";
	public static final String CANT_BE_GREATER_THAN_REMAINING_PAYMENT_TIMES = "CANT_BE_GREATER_THAN_REMAINING_PAYMENT_TIMES";

	public static final String INVALID_PRODUCT = "INVALID_PRODUCT";

	public static final String START_DATE_REQUIRED = "START_DATE_REQUIRED";
	public static final String END_DATE_REQUIRED = "END_DATE_REQUIRED";
	public static final String EMPTY_SPORTMANLIST = "EMPTY_SPORTMANLIST";

	public static final String ANSWER_SURVERY_QUESTION = "ANSWER_SURVERY_QUESTION";

	public static final String BIRTH_CERTIFICATION_ATTACH_IS_REQUIRED = "BIRTH_CERTIFICATION_ATTACH_IS_REQUIRED";
	public static final String TOTAL_SUMINSURED_OF_CHILD_MUST_BE_BETWEEN_10LAKH_1000LAKH = "TOTAL_SUMINSURED_OF_CHILD_MUST_BE_BETWEEN_10LAKH_1000LAKH";
	public static final String INVALID_INSURED_DOB = "INVALID_INSURED_DOB";
	public static final String CHILD_AGE_MUST_BE_BETWEEN_30DAYS_AND_12YEARS = "CHILD_AGE_MUST_BE_BETWEEN_30DAYS_AND_12YEARS";
	public static final String INVALID_MOTHER_DOB = "INVALID_MOTHER_DOB";
	public static final String INVALID_FATHER_DOB = "INVALID_FATHER_DOB";
	public static final String IDNO_MUST_NOT_BE_DUPLICATE = "IDNO_MUST_NOT_BE_DUPLICATE";
	public static final String CUSTOMER_AGE_MUST_BE_BETWEEN = "CUSTOMER_AGE_MUST_BE_BETWEEN";
	public static final String EXISTING_CUSTOMER_PLZ_SELECT = "EXISTING_CUSTOMER_PLZ_SELECT";

	public static final String MEDICAL_CHECK_UP_IS_REQUIRED = "MEDICAL_CHECK_UP_IS_REQUIRED";
	public static final String CLS_OF_HEALTH_REQUIRED = "CLS_OF_HEALTH_REQUIRED";

	public static final String ALREADY_ADD_DISABILITYPART = "ALREADY_ADD_DISABILITYPART";
	public static final String ADD_PERCENTAGE = "ADD_PERCENTAGE";

	public static final String LIFE_ClAIM_PROCESS_SUCCESS = "LIFE_ClAIM_PROCESS_SUCCESS_PARAM";
	public static final String DEATH_DISABILITY_CHOOSE = "DEATH_DISABILITY_CHOOSE";
	public static final String LIFE_ClAIM_NOTIFICATION_PROCESS_SUCCESS = "LIFE_ClAIM_NOTIFICATION_PROCESS_SUCCESS";
	public static final String LIFE_ClAIM_NOTIFICATION_PROCESS_UPDATE = "LIFE_ClAIM_NOTIFICATION_PROCESS_UPDATE";
	public static final String LIFE_ClAIM_APPROVAL_SUCCESS = "LIFE_ClAIM_APPROVAL_SUCCESS";

	public final static String LIFE_ClAIM_INFORM_SUCCESS = "LIFE_ClAIM_INFORM_SUCCESS_PARAM";
	public final static String LIFE_ClAIM_CONFIRM_SUCCESS = "LIFE_ClAIM_CONFIRM_SUCCESS";
	public final static String LIFE_ClAIM_PAYMENT_SUCCESS = "LIFE_ClAIM_PAYMENT_SUCCESS";
	public final static String POLICY_OVER_ONEYEAR = "POLICY_STARTDATE_IS_NOT_OVER_ONEYEAR";

	public final static String PAYMENT_PROCESS_SUCCESS_PARAM = "PAYMENT_PROCESS_SUCCESS_PARAM";
}
